server {
    listen       80;
    server_name  _;
    root   /usr/share/nginx/html;
    index  index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: increase buffer sizes for large assets
    location ~* \\.(?:manifest|appcache|html|xml|json)$ {
        add_header Cache-Control "no-store";
    }
}
